# This is a basic workflow to help you get started with Actions
name: Example

on: 
  push:
    branches: [master]

jobs:
  mi-segundo-job:
    name: Mi Segundo Job
    runs-on: ubuntu-latest
    steps:
      - name: Leer prueba.txt
        id: Prueba
        with:
          path: ./Prueba.txt
      - name: Echo Prueba.txt
        env:
          TEXT: ${{steps.Prueba.outputs.Prueba}}
        run: echo $TEXT
  
