# This is a basic workflow to help you get started with Actions
name: Example

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
steps:
  - name: Leer prueba.txt
    id: Prueba
    with:
      path: ./Prueba.txt
  - name: Echo Prueba.txt
    env:
      TEXT: ${{steps.Prueba.outputs.Prueba}}
    run: echo $TEXT
  
